name: Vite build

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master, develop]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [21.4.0]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                version: 8

            - name: Install dependencies
              run: pnpm install

            - name: Check linting
              run: pnpm run lint

            - name: Build
              run: pnpm run build