name: Vite build

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master, develop]

jobs:
    cache-and-install-pnpm:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.15.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                version: 8
            #     run_install: false

            # - name: Get pnpm store directory
            #   shell: bash
            #   run: |
            #     echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            #     - uses: actions/cache@v3
            #     name: Setup pnpm cache
            #     with:
            #       path: ${{ env.STORE_PATH }}
            #       key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
            #       restore-keys: |
            #         ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

    build:
      needs: cache-and-install-pnpm
      runs-on: ubuntu-latest

      steps:
        - name: Check linting
          run: pnpm run lint

        - name: Build
          run: pnpm run build